/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_javx_Javx */

#ifndef _Included_org_javx_Javx
#define _Included_org_javx_Javx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_javx_Javx
 * Method:    add_int
 * Signature: ([I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_javx_Javx_add_1int
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
